### PR TITLE
Fixing focusing issues when switching between EXWM and emacs buffers

### PR DESCRIPTION
**Pull request by moritzschaefer**
Title says it all. 

Please merge, to end the misery described in #759

### CODE REVIEW

**Comment by Stebalien** [comment]
I'm somewhat concerned that this has power-consumption implications. Is `_NET_WM_STATE_HIDDEN` used as a hint to GUI applications to suspend battery-intensive operations? Or is "iconification" enough? I know that Firefox, at least, uses reduces power consumption when hidden.

**Comment by moritzschaefer** [comment]
I understand. Thank you for raising your concerns.

I will have a look at this PR later this month and report back.

**Comment by medranocalvo** [comment]
I don't feel confortable merging this, to be frank.  The commented code stems from this change: 3dbf1b1bed96d9ac3ee2718134ded619f46951bb, where support for _NET_WM_STATE_HIDDEN is implemented.  Obviously there's a bug, but what is it?  This PR is not based on an understanding of the issue, nor does it fix the bug; it seems to me that it tries to hide it.

On the other hand I understand that the issue persists since years and no-one has stepped up to fix it.  Deciding "let's wait for somewhat with interest and means to fix it" might be impractical.  I am open to opinions on how to handle this.

**Comment by moritzschaefer** [comment]
@medranocalvo I understand that this is not the proper way and closed the PR. Thank you for the feedback. I will still try to have a look into it, but can't promise anything. Especially since my EXWM/Emacs/X11 skills are limited

**Comment by medranocalvo** [comment]
Yes, debugging EXWM issues is hard, and this must be one of the difficult ones (even @ch11ng could not fix it!).  Let's continue discussion and share efforts in #759.

**Pull request closed without merging**
