### PR TITLE
Catch and report all errors raised when invoking command hooks 

### LINKED ISSUE #842: `Args out of range: [], 0` when clicking X window during isearch
Thanks for the great package and your work on it! 🙏🏾  I've got an issue that's been bothering me for a bit, but I haven't gotten around to reporting it before now. I couldn't find anyone else reporting the same issue.

## Problem

If I abort an isearch in progress (in a normal Emacs buffer) by clicking on an X window, I get this error in the minibuffer and one of two unwanted outcomes.

```
Args out of range: [], 0
```

The outcome is one of:

1. All X windows (also new ones) stop responding to all mouse input. Keyboard input still works, but they don't respond to mouse events at all. Only way I've found to fix this is to restart Emacs.
2. Emacs freezes completely. `kill -12 <emacs pid>` may be able to get you out of it.

## Steps to reproduce

- start an `isearch` (`C-s`) in a regular Emacs buffer
- without running `isearch-exit`, move your mouse to an X window and focus it by clicking.

I'm currently unsure whether this only occurs when clicking an X window on a different monitor or not. I'll check this as soon as I've posted this issue.

## System info etc 

- emacs version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.16.0)

- os: Linux, NixOS, 21.05 (but this issue has been there for a while)

- exwm-version: 45ac28cc9cffe910c3b70979bc321a1a60e002ea

----

Anything else you'd like to know, just ask and I'd be happy to supply what info I can! 😄

### PR DESCRIPTION
**Pull request by ArneBab**
This should fix https://github.com/ch11ng/exwm/issues/842 (according to the discussion in the issue). I just nabbed this commit from https://github.com/daviwil/exwm/commit/7b1be884124711af0a02eac740bdb69446bc54cc

### CODE REVIEW

**Comment by medranocalvo** [comment]
@ArneBab, Thank you for bringing this up.  I believe that need permission from @daviwil is needed, or at least warranted.
@daviwil, would you like this change to be merged into EXWM?

**Comment by daviwil** [comment]
Yes! However, is it small enough to not require FSF copyright assignment? I still haven't arranged that yet.

**Comment by medranocalvo** [comment]
@daviwil, great!  Yes, it's not needed for small changes, but will be needed in the future.  I'd like more contributions from you!

For perspective, starting the assignment process involves sending an e-mail:

> To: [assign@gnu.org](mailto:assign@gnu.org)
> 
>     REQUEST: SEND FORM FOR PAST AND FUTURE CHANGES
> 
>     [What is the name of the program or package you're contributing to?]
>     GNU Emacs and GNU ELPA.
>     [Did you copy any files or text written by someone else in these changes? Even if that material is free software, we need to know about it.]
> 
>     [Do you have an employer who might have a basis to claim to own your changes? Do you attend a school which might make such a claim?]
> 
>     [For the copyright registration, what country are you a citizen of?]
> 
>     [What year were you born?]
> 
>     [Please write your email address here.]
> 
>     [Please write your postal address here.]
> 
>     [Which files have you changed so far, and which new files have you written so far?]

Then it gets more painstaking: signatures are needed.  (Accommodations can be made if necessary, AFAIU.)

More details at https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html

---

I'll complete the submission and merge as time permits.  (Might take some time.)  Thank you both @ArneBab and @daviwil.

**Comment by daviwil** [comment]
Yep, I've already got the process started with the FSF for both Emacs and Guile but I still need to bug a VP at my employer to approve it :/  Probably won't happen very soon!  Hopefully this change is mergeable without it.

**Comment by medranocalvo** [comment]
Force-pushed with the following changes:
- simplify code using `xcb-debug:backtrace`
- run `post-command-hook` even if `pre-command-hook` fails.  (Is this incorrect?)
- adjusted commit message
Please test again with a failing hook.

**Comment by ArneBab** [comment]
I merged your changes. @daviwil can you test whether it still works for you?

**Comment by medranocalvo** [comment]
I merged this change into master (post 0.28).

Thank you @daviwil for the fix and thank you @ArneBab for making it happen.

**Pull request closed without merging**
