### PR TITLE
New variable: exwm-xim-buffer-p

### PR DESCRIPTION
**Pull request by tumashu**
* exwm-xim.el (exwm-xim-buffer-p): New variable.
(exwm-xim--handle-forward-event-request): Add exwm-xim-buffer-p

### CODE REVIEW

**Comment by tumashu** [comment]
At the moment, I use the below function, but seem to be not a good solution, so I suggest add this variable.
```
(defun pyim-exwm-enable-p ()
  "测试当前是否是 exwm 环境。

FIXME: This seem to be not a good approach, the
better way is let exwm provide a test function."
  (string-match-p " \\*temp\\*" (buffer-name))
  (bound-and-true-p exwm-xim-buffer-p))

```

**Comment by medranocalvo** [comment]
Hello @tumashu.  This looks good, thank you very much.  I'll merge it once I figure out how to move EXWM forward while @ch11ng is away.

**Comment by medranocalvo** [comment]
I have released 0.25 with latest @ch11ng changes.  Will release 0.26 with your changes ASAP after 0.25 is in GNU ELPA.

**Comment by tumashu** [comment]
good job :-)

在 2021-10-30 07:24:50，medranocalvo ***@***.***> 写道：


I have released 0.25 with latest @ch11ng changes. Will release 0.26 with your changes ASAP after 0.25 is in GNU ELPA.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by medranocalvo** [comment]
@tumashu: you are a long time contributor to EXWM but as far as I can see this was your first commit.  Congratulations!

I'll be happy to continue to see you around here.

(Please think about starting the copyright assignment paperwork if you have not done so.)

**Comment by tumashu** [comment]
i have signed paper

**Comment by medranocalvo** [comment]
Oh, that's great.  (I didn't bother to check because the change was tiny.)

By the way, please add an entry about `pyim` in the wiki (https://github.com/ch11ng/exwm/wiki#third-party-extensions) noting the special integration with EXWM.

**Pull request merged**
