### PR TITLE
Fix frame focus for Emacs 29

### PR DESCRIPTION
**Pull request by mgi**
See https://debbugs.gnu.org/cgi/bugreport.cgi?bug=58438 for more details

### CODE REVIEW

**Comment by medranocalvo** [comment]
Hello @mgi,

I've read the discussion on #889.  In my opinion this fix is correct and necessary, although there appear to be further issues in the area.

I added a new commit that reverts back to your first version modifying it a bit.  Please have a look and modify as you see fit.

If you are OK with the changes (incl. commit message Thanks-To, which might be more personal), I propose that you rebase & commit under your name, if that's OK for you.

Contributions to EXWM usually need copyright assignment to the FSF.  Please let me know (privately if you prefer) whether you have already assigned it for changes to Emacs.  If not, please consider doing it, as I must require it for further contributions.  In other words: I appreciate your fix and would like more of your help with EXWM.

Copyright assignment is not needed for this change.

In any case, this ch

**Comment by mgi** [comment]
medranocalvo ***@***.***> writes:

> Hello @mgi,
>
> I've read the discussion on #889.  In my opinion this fix is correct
> and necessary, although there appear to be further issues in the area.
>
> I added a new commit that reverts back to your first version modifying
> it a bit.  Please have a look and modify as you see fit.

Hi @medranocalvo,

I've just your new patch and it also works for me too.

> If you are OK with the changes (incl. commit message Thanks-To, which
> might be more personal), I propose that you rebase & commit under your
> name, if that's OK for you.

Find by me.  But I'll think I need some instructions to the "rebase &
commit under your name" part 😅

> Contributions to EXWM usually need copyright assignment to the FSF.
> Please let me know (privately if you prefer) whether you have already
> assigned it for changes to Emacs.

I already have the paperwork done for FSF.

> If not, please consider doing it, as I must require it for further
> contributions.  In other words: I appreciate your fix and would like
> more of your help with EXWM.

Thanks for the kind words.  I'll try to help AFAIC.
-- 
Manuel Giraud

**Comment by leungbk** [comment]
Thanks for your work on this. I've tried the latest version of this branch, and it almost always works, save for when I am in the middle of a `consult-buffer` session and the current candidate is an EXWM buffer that is being [live-previewed](https://github.com/minad/consult#live-previews). 

I can work around this for now by disabling live preview for any `consult` command that might raise an EXWM buffer.

**Comment by leungbk** [comment]
> Find by me. But I'll think I need some instructions to the "rebase & commit under your name" part 😅

In the Magit transient popup for committing (`c`), the `-A` flag allows you to commit under a different name. Alternatively, you might be able to modify the name of the author in the course of an interactive rebase by editing the name of the author in the `COMMIT_EDITMSG` buffer (haven't tested this).

**Comment by Stebalien** [comment]
This goes a bit haywire with miniframe because it's not an EXWM workspace. One solution is to just iterate over all frames:

```elisp
          (dolist (f (frame-list))
            (let ((strid (number-to-string id)))
              (when (string-equal strid (frame-parameter f 'outer-window-id))
                (x-focus-frame f t)))))))
```

**Comment by mgi** [comment]
Steven Allen ***@***.***> writes:

> This goes a bit haywire with miniframe because it's not an EXWM
> workspace. One solution is to just iterate over all frames:

Do you mean with the mini-frame package from melpa?
-- 
Manuel Giraud

**Comment by Stebalien** [comment]
Ah, yes.

**Comment by mgi** [comment]
Ok.  I've just tested with mini-frame-mode and yes, it does not work at
all.  In my setup, the completion frame ends up under the xterm (for
instance) and so is invisible.  I've replace `exwm-workspace--list` with
`(frame-list)` in the current version of #890 (as you suggested) but it
does not work for me.

I agree with Adrián that this patch is not complete (as it does not work
with every package under the sun) but it could applied as it is a
progress on current emacs anyway.
-- 
Manuel Giraud

**Comment by medranocalvo** [comment]
@mgi: merged!  Thank you very much.  I'll wait for #867 before making the release.

Indeed there is much to do for Emacs 29, this is another step in that direction.

@Stebalien, I thought child frames were not supported in EXMW; do you use `mini-frame-standalone`?  In any case, please open a new ticket (just copy-paste the above) and tag it with emacs-29.

@leungbk, please open a new ticket as well.

**Comment by Stebalien** [comment]
> do you use mini-frame-standalone?

Yes. I'll open a new ticket.

(but honestly, I just stopped using mini-frame entirely due to other focus issues that have nothing to do with EXWM)

**Comment by medranocalvo** [comment]
@mgi: 0.27 has been released, featuring your changes.  Thank you very much!

**Comment by mgi** [comment]
Thank you!
-- 
Manuel Giraud

**Pull request closed without merging**
